Algoritmo "medida"

Var
a,b,c , areaQuadrado ,areaTriangulo,areaTrapezio: real



Inicio

escreva("Digite a medida A: ")
leia(a)
escreva("Digite a medida B: ")
leia(b)
escreva("Digite a medida C: ")
leia(c)



areaQuadrado <- a * a
areaTriangulo <- (a * b) / 2
areaTrapezio <- (a + b) * 6 / 2



escreval("AREA DO QUADRADO = ",areaQuadrado:6:4)
escreval("AREA DO TRIANGULO = ",areaTriangulo:6:4)
escreval("AREA DO TRAPEZIO = ",areaTrapezio:6:4)



Fimalgoritmo